### PR TITLE
Subtitlefinder changes

### PR DESCRIPTION
**Pull request by larsjohnsen**

### CODE REVIEW

**Comment by xylosper** [comment]
Can you make a brief description about the purpose of this pull request?

**Comment by larsjohnsen** [comment]
This fixes the subtitlefinder in read-only environments, adds option to not place subtitles in media file directory, and makes it faster to use by autoselecting the first result.

**Comment by xylosper** [comment]
Your code creates a temporary file when `nativeFile` is not writable, but I don't think this is a good idea.
First of all, it's not temporary because it's not removed explicitly. Also, non-temporary file will be better for restoring of subtitle selection.
Second of all, some Linux distros such as Arch Linux bind /tmp to ramdisk, so eventually the downloaded file will be deleted and it cannot be restored.

I think it's better to add another option to specify fallback directory.
And, if fallback directory wouldn't work, just pop an error message.

And, what for is the option `Save downloaded subtitles`?
How different is `save subtitles` from `download subtitles`?

**Comment by larsjohnsen** [comment]
> First of all, it's not temporary because it's not removed explicitly.
True. The file can just as well saved to ~/.config/xylosper/bomi/subtitles and deleted when the associated history index expires (if that's the case).

> And, what for is the option Save downloaded subtitles?
The option "Save downloaded subtitles" could more precisely be named "Save fetched subtitles to belonging media file directory". Having an option for that is nice if one wishes to keep the directory clean.

**Comment by xylosper** [comment]
> "Save fetched subtitles to belonging media file directory"

Ah, so you're using temporary file. But your code cannot tell the readonly situation from don't save situation.

I can merge this but as I said, I need to add an alternative for read-only case and popup message on error.
Is that okay?

**Comment by xylosper** [comment]
Also, please don't add spaces in file name. an hyphen would be enough.

**Comment by larsjohnsen** [comment]
> But your code cannot tell the readonly situation from don't save situation.

`auto writable = nativeFile.open(QFile::WriteOnly | QFile::Truncate);` should determine the readonly situation.

> I can merge this but as I said, I need to add an alternative for read-only case and popup message on error.
Is that okay?

Please do!

**Comment by xylosper** [comment]
> auto writable = nativeFile.open(QFile::WriteOnly | QFile::Truncate); should determine the readonly situation.

I mean, for user. You code just fallback to temporary file if it's readonly which is the user doesn't want. That's why fallback directory or error message needed.

**Comment by larsjohnsen** [comment]
I agree.

**Comment by xylosper** [comment]
Merged. Thank you!

**Pull request merged**
